config/routes.rb
RailsTracePanel::Engine.routes.draw do
  root to: "traces#index"
  get "traces", to: "traces#index"
  get "traces/:id", to: "traces#show", as: :trace
  delete "traces", to: "traces#destroy_all"
end

app/controllers/rails_trace_panel/traces_controller.rb
module RailsTracePanel
  class TracesController < ActionController::Base
    def index
      Datadog::Tracing.reject!
      filters = {
        id: params[:id],
        service: params[:service],
        error: params[:error] == "true",
        min_duration: (params[:min_duration] || RailsTracePanel.configuration.min_span_duration_threshold)&.to_f,
        query: params[:query].presence
      }

      @traces = RailsTracePanel::Store.filtered_traces(100, filters)
    end

    def show
      Datadog::Tracing.reject!
      @traces = RailsTracePanel::Store.recent_traces(100, id: params[:id])
    end

    def destroy_all
      Datadog::Tracing.reject!
      RailsTracePanel::Store.clear
      redirect_to traces_path, notice: "All traces cleared"
    end
  end
end

app/helpers/rails_trace_panel/traces_helper.rb
module RailsTracePanel::TracesHelper

  def to_ms(s)
    ms = (s * 1000).round(1)
    if ms > 1000
      "#{(ms / 1000).round(1)}s"
    else
      "#{ms}ms"
    end
  end

  def render_span_summary(span, trace)
    color = service_color(span.service)

    content_tag(:div, class: "span-header") do
      safe_join([
        content_tag(:span, "#{span_type_emoji(span.type)}", alt: span.type),
        content_tag(:span, "#{span.service}", class: "service-tag", style: "color: #{color}"),
        content_tag(:span, "#{span.name}", class: "name-tag"),
        content_tag(:span, "#{span.resource.truncate(100)}", class: "bold"),
        content_tag(:span, to_ms(span.duration), class: "muted"),
        # content_tag(:span, "start: #{span.root? ? span.start : to_ms(Time.parse(span.start) - Time.parse(trace.root&.start)) }"),
        (content_tag(:span, "start: #{Time.parse(span.start).strftime("%H:%M:%S.%L")}", class: "muted") if span.root?),
        (content_tag(:span, "parent: #{span.parent_id}", class: "muted") if span.root?),

        (content_tag(:span, "route: #{span.meta["http.route"]}") if span.meta["http.route"] && span.meta["http.route"] != span.meta["http.url"]),
        (content_tag(:span, "url: #{span.meta["http.url"]}", class: "bold") if span.meta["http.url"]),
        (content_tag(:span, "error.type: #{span.meta["error.type"]}", class: "bold") if span.meta["error.type"]),
        (content_tag(:span, "error.message: #{span.meta["error.message"]}") if span.meta["error.message"]),
        (content_tag(:span, "error.stack: #{span.meta["error.stack"][0..300]}") if span.meta["error.stack"]),
        (content_tag(:span, "active_record.instantiation.class_name: #{span.meta["active_record.instantiation.class_name"]}", class: "bold") if span.meta["active_record.instantiation.class_name"]),
        # content_tag(:pre, "META: #{JSON.pretty_generate(span.meta)}"),
        (content_tag(:span, "⚠️ error", class: "error") if span.status == 1),
        (content_tag(:pre, span.resource, class: "sql", "x-show": "sql") if span.resource.length > 100 || span.resource.include?("\n") || span.type == "sql"),
      ].compact, " ")
    end
  end

  def render_span_bar(span, trace)
    color = service_color(span.service)
    width_percent = duration_percent(span, trace)
    offset = duration_offset(span, trace)

    content_tag(:div, "",
      class: "bar",
      style: "left: #{offset}%;width: #{width_percent}%; background-color: #{color.gsub(")", " / 25%)")}; border: 1px solid #{color.gsub(")", " / 33%)")};")
  end

  def render_span_tree(span, trace)
    content_tag(:li) do
      content_tag(:details, open: span.children.any?) do
        safe_join([
          content_tag(:summary) do
            render_span_bar(span, trace) +
            render_span_summary(span, trace)
          end,
          content_tag(:ul) do
            safe_join(span.children.map { |child| render_span_tree(child, trace) })
          end
        ])
      end
    end
  end

  def span_type_emoji(type)
    {
      "http" => "🌐",
      "web" => "🧭",
      "custom" => "🛠️",
      "browser" => "🧪",
      "worker" => "🧵",
      "db" => "🗄️",
      "sql" => "🗄️",
      "" => "",
    }[type.to_s] || "❓(#{type})"
  end

  def duration_offset(span, trace)
    offset =
      if trace.is_a?(Numeric)
        nil
      else
        trace&.root&.start
      end

    return 0 unless offset

    offset = Time.parse(span.start) - Time.parse(offset)
    offset = offset
    offset = (offset.to_f / trace.root.duration.to_f) * 100
    offset.round(1)
  end

  def duration_percent(span, trace)
    duration =
      if trace.is_a?(Numeric)
        trace
      else
        trace&.root&.duration
      end

    return 100 unless duration
    ((span.duration.to_f / duration.to_f) * 100).round(1)
  end

  def service_color(service)
    @service_colors ||= {}
    @service_colors[service] ||= begin
      hash = Zlib.crc32(service.to_s)
      h = (hash % 360)
      "hsl(#{h} 60% 60%)"
    end
  end


  def draw_span_tree(span)
    return draw_span_header(span) if span.children.empty?
    tag.details do
      safe_join([
        tag.summary { draw_span_header(span) },
        draw_span_list(span.children)
      ], "\n")
    end
  end

  def draw_span_list(list)
    tag.div(style: "margin-left: 1rem") do
      tag.ul do
        safe_join(
          list.map do |span|
            tag.li { draw_span_tree(span) }
          end,
          "\n"
        )
      end
    end
  end
end

app/views/rails_trace_panel/traces/_head.html.erb
<style>
  html, body, details, summary, ul, li { padding: 0; margin: 0; box-sizing: border-box; border: 0; font-size: 100%; }
  body { font-family: sans-serif; margin: 20px; background-color: #f5f5f5; font-size: 14px; }
  h1 { font-size: 24px; margin-bottom: 1rem; }
  .trace {
    margin-bottom: 1.5rem;
    padding: 1rem;
    border: 1px solid #ccc;
    border-radius: 8px;
    background: white;
    display: block;
    position: relative;
  }
  .error { color: red; }
  li { list-style-type: none; margin-left: 0.1rem; position: relative; padding-left: 0.1rem; border-left: 1px solid #EEE; }
  summary {
    cursor: pointer;
    display: flex;
    flex-direction: column;
    position: relative;
    margin: 0.5rem 0.1rem;
    padding: 0.5rem;
  }
  .bar {
    height: 2rem;
    background-color: #4caf50;
    border-radius: 4px;
    margin-bottom: 0.5rem;
    position: absolute;
    z-index: 0;
    inset: 2px;
    left: 0;
    top: 0;
    height: 100%;
  }
  .span-header {
    display: inline-flex;
    flex-wrap: wrap;
    gap: 1rem;
    align-items: center;
    z-index: 1;
    position: relative;
  }
  .service-tag { border-radius: 4px; font-size: 0.85rem; font-weight: bold; }
  [x-cloak] { display: none; }
  .bold { font-weight: 600; }
  .name-tag { font-style: italic; }
  .muted { color: #999; }
  a { text-decoration: none; color: inherit; }
  .alert {
    padding: 1rem; margin: 1rem 0; border-radius: 4px;
    background-color: #f8d7da; color: #721c24; border: 1px solid #f5c6cb;
  }
  .sql {
    border-left: 4px solid #EEE; padding: 1rem; margin: 1rem 0;
    white-space: pre-wrap;
    word-break: break-word;
    background-color: #f9f9f9;
    width: 100%;
    border: 1px solid #ccc;
    font-family: monospace;
  }

  .sql-hl-keyword {
    color: #005cc5; /* azul intenso */
    font-weight: bold;
  }

  .sql-hl-function {
    color: #d73a49; /* rojo suave */
  }

  .sql-hl-number {
    color: #005cc5; /* azul */
  }

  .sql-hl-string {
    color: #032f62; /* azul oscuro tirando a gris */
    font-style: italic;
  }

  .sql-hl-special {
    color: #6f42c1; /* púrpura */
  }

  .sql-hl-bracket {
    color: #999; /* gris sutil */
  }

  .sql-hl-comment {
    color: #6a737d; /* gris */
    font-style: italic;
    opacity: 0.9;
  }
</style>
<script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.14.8/dist/cdn.min.js"></script>

<title>Rails Trace Panel</title>


<script type="module">
  import { highlight } from 'https://cdn.jsdelivr.net/npm/sql-highlight@6.0.0/+esm'


  document.addEventListener('DOMContentLoaded', () => {
    // Get all elements with the class 'sql'
    const sqlElements = document.querySelectorAll('.sql');
    console.log(sqlElements)

    // Loop through each element
    sqlElements.forEach((element) => {
      // Get the text content of the element
      const sqlString = element.textContent;

      // Highlight the SQL string
      const highlighted = highlight(sqlString, { html: true });

      // Replace the content of the element with the highlighted SQL
      element.innerHTML = highlighted;
    });
  });
</script>

app/views/rails_trace_panel/traces/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render "head" %>
</head>
<body x-data="{ debug: false, toggleAll(open) { document.querySelectorAll('details').forEach(d => d.open = open) } }" @keydown.window.meta.shift.d="debug = !debug">
  <div style="display: flex; justify-content: space-between; margin-bottom: 1rem; align-items: center;">
    <a href="<%= traces_path %>"><h1>Rails Trace Panel</h1></a>
    <%= form_tag traces_path, method: :delete, data: { confirm: "Are you sure?" } do %>
      <%= submit_tag "Delete all traces" %>
    <% end %>
  </div>
  <% flash.each do |type, message| %>
    <div class="alert alert-<%= type %>">
      <%= message %>
    </div>
  <% end %>

  <% if @traces.empty? %>
    <p><em>No traces saved yet.</em></p>
  <% else %>
    <% @traces.each_with_index do |trace, idx| %>
      <a class="trace" style="gap: 1rem; display: flex; flex-direction: column; padding: 0.5rem" href="<%= trace_path(trace.id) %>">
        <% trace.root_spans.each do |span| %>
          <div style="position:relative; padding: 0.2rem 1rem;">
            <%= render_span_bar(span, 30) %>
            <%= render_span_summary(span, trace) %>
          </div>
        <% end %>
      </a>
    <% end %>
  <% end %>
</body>
</html>

app/views/rails_trace_panel/traces/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render "head" %>
</head>
<body x-data="{
  debug: false,
  sql: false,
  toggleAll(open) { document.querySelectorAll('details').forEach(d => d.open = open) }
}" @keydown.window.meta.shift.d="debug = !debug">
  <a href="<%= traces_path %>"><h1>Rails Trace Panel</h1></a>

  <div style="margin-bottom: 1rem;">
    <button @click="toggleAll(true)">Expand all</button>
    <button @click="toggleAll(false)">Collapse all</button>
    <button @click="sql = true">Show Sql</button>
    <button @click="sql = false">Hide Sql</button>
  </div>

  <% if @traces.empty? %>
    <p><em>No traces saved yet.</em></p>
  <% else %>
    <% @traces.each_with_index do |trace, idx| %>
      <div class="trace">
        <% trace.root_spans.sort_by(&:start).each do |span| %>
          <%= render_span_tree(span, trace) %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</body>
</html>